config/routes.rb
Rails.application.routes.draw do
  get "/ask", to: "questions#ask"
  get "/answer", to: "questions#answer"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def ask
  end
  
  def answer
    @question = params[:question]
    case @question
      when ""
        @answer = "String Vacio"
      when "I am going to work"
        @answer = "Great"
      else
        if @question.include?("?")
            @answer = "Silly question, get dressed and go to work!"
          else
            @answer = "I don't care, get dressed and go to work!"
        end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="container text-center">
<h1 class="m-4" >Stupid coaching!</h1>
  <div class="question p-4 mt-5 ml-4 mx-auto">
    <h4> <%= @question %> </h4>
    <p> -You </p>
  </div>

  <div class="answer mx-auto p-4 mt-5 ml-4 mb-4">
    <h4> <%=  @answer %></h4>
    <p> -Your Coach </p>
  </div>

  <%= link_to "New Ask", ask_path %>
</div>

app/views/questions/ask.html.erb
<div class="container text-center">
  <h1>Stupid Coach</h1>
  <form action="/answer" method="get">
    <input class="mt-3"type="text" name="question">
    <input class="btn btn-dark" type="submit" value="Ask!">
  </form>
</div>